import { ArrowLeft, CalendarRange, Droplets, Dumbbell, Flame, History, Utensils } from 'lucide-react'
import { AICommentCard } from '../components/planner/AICommentCard'
import { selectDailyPlanTargetRows } from '../planner/planSelectors'
import type { FatLossPlan, PlanVersion } from '../planner/types'

export function PlanDetailPage({ plan, version, onBack, onWeeklyReview, onHistory }: { plan: FatLossPlan; version: PlanVersion; onBack: () => void; onWeeklyReview: () => void; onHistory: () => void }) {
  const energyRows = selectDailyPlanTargetRows(version)
  const sourceLabel = version.energyPlan ? { wearable_logs: '最近裝置紀錄', profile_wearable_average: '問卷裝置平均', mifflin: '基本資料公式估算' }[version.energyPlan.source] : undefined
  return <section className="planner-stack-page"><header className="planner-stack-header"><button aria-label="返回首頁" onClick={onBack}><ArrowLeft /></button><div><p className="eyebrow">CURRENT PLAN</p><h1>{plan.name}</h1></div></header><div className="plan-detail-hero health-card"><span>目前版本自 {version.effectiveFrom} 生效</span><strong>{version.calorieTargetKcal.toLocaleString('zh-TW')} <small>kcal／日</small></strong><p>目標 {plan.goalWeightKg.toFixed(1)} kg · 預計至 {version.goalDate}</p></div><article className="plan-energy-card health-card" aria-labelledby="plan-energy-title"><div><span>DAILY ENERGY</span><h2 id="plan-energy-title">每日熱量分析</h2></div><div className="plan-energy-table-scroll"><table><thead><tr><th scope="col">項目</th><th scope="col">kcal／日</th><th scope="col">性質</th></tr></thead><tbody>{energyRows.map((row) => <tr key={row.key}><th scope="row">{row.label}</th><td>{row.valueKcal.toLocaleString('zh-TW')}</td><td>{row.kind === 'target' ? '目標／參考' : '估計'}</td></tr>)}</tbody></table></div><p>{version.energyPlan ? `${sourceLabel} · 信心度 ${version.energyPlan.confidence === 'high' ? '高' : version.energyPlan.confidence === 'medium' ? '中' : '低'}。` : '這是較早版本，尚未保存活動與靜止能量估計。'}活動與靜止能量不是每天必須追到的處方。</p></article><div className="plan-detail-grid">{[[Flame, '熱量範圍', `${version.calorieRangeMinKcal}–${version.calorieRangeMaxKcal} kcal`], [Utensils, '蛋白質', `${version.proteinMinG}–${version.proteinMaxG} g`], [Droplets, '飲水', `${version.waterTargetMl} ml`], [CalendarRange, '每週速度', `${version.expectedWeeklyLossKg.toFixed(1)} kg`], [Dumbbell, '每週活動', `有氧 ${version.aerobicMinutesPerWeek} 分 · 肌力 ${version.strengthDaysPerWeek} 次`], [History, '晚間預留', `${version.eveningReserveKcal} kcal`]].map(([Icon, label, value]) => { const ItemIcon = Icon as typeof Flame; return <article className="health-card" key={String(label)}><ItemIcon /><span>{String(label)}</span><strong>{String(value)}</strong></article> })}</div><AICommentCard comment={version.comment} /><div className="planner-page-actions"><button className="primary" onClick={onWeeklyReview}>本週檢討</button><button onClick={onHistory}>查看計畫歷史</button></div></section>
}
